/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.lostbearlabs.gonzo

import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test

class AppTest {
    @Test fun `make sure assertJ is available`() {
        assertThat(2+2).isEqualTo(4)
    }
}
